// Generated by CoffeeScript 1.4.0
(function() {
  var handleRequest, server;

  handleRequest = function(req, res) {
    res.writeHead(200, {
      "content-type": "text/plain"
    });
    res.write("Hello world!");
    return res.end();
  };

  server = require("http").createServer();

  server.on("request", handleRequest);

  server.listen(8080);

}).call(this);
