// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, port, rest, sys;

  express = require("express");

  sys = require("util");

  rest = require("./node_modules/restler");

  app = express.createServer(express.logger());

  app.get("/", function(request, response) {
    rest.get("http://google.com").on("complete", function(result) {});
    if (result instanceof Error) {
      sys.puts("Error: " + result.message);
      this.retry(5000);
    } else {
      sys.puts(result);
    }
    return response.send("OMG Hello World!");
  });

  port = process.env.PORT || 5000;

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
